app = "lumi-live"
primary_region = "ewr"

[build]

[deploy]
  release_command = "npx prisma db push --skip-generate"

[processes]
  web = "npm run start"
  worker = "npm run worker"

[env]
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://lumi-live.fly.dev"
  LUMI_USE_MOCK_FALLBACK = "false"
  INGEST_POLL_MINUTES = "30"

[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  processes = ["web"]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  processes = ["worker"]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
